### ISSUE TITLE
React Native projects support

### ISSUE THREAD

**Issue by apporc** [hsanson/vim-android#100]
For react native projects, the project root directory for vim-android is in fact located at the `project root/android`, instead of `project root`. Currently the only way to detect the project is to `cd` into the android dir and open a separate vim window. If the project root is configurable, then one can edit react code and java code with one single vim window.

**Comment by sultanahamer** [comment]
@hsanson I have worked on both react native projects and android native projects. The question from @apporc is that, if they open vim at say path `~/Projects/MyCoolReactNativeProject` to work on the javascript files(react native is basically written in js or typescript files), can they in the same instance of vim open android java files which will be at the path `~/Projects/MyCoolReactNativeProject/android/build.gradle`

I have created a test react native project to test this scenario and here are my findings.

First time when we open, we have to open vim pointing to `~/Projects/MyCoolReactNativeProject/android/` directory.
1. Open some java file here
2. Gradle sync
3. Generate classpath
4. Gradle build
5. AndroidInstall debug

after this, we can start vim at parent directory `~/Projects/MyCoolReactNativeProject/` and everything goes alright except this one problem

AndroidInstall does not work because it is not able to find the apk file from parent directory because of this command and here is the fix

**Existing code**:
```  let l:apk = system('find $(pwd)/*/build/** -name "app-' . a:mode . '.apk" | tr "\n" " " | tr "//" "/"')```

**Fix**:
```  let l:apk = system('find $(pwd)/**/build/** -name "app-' . a:mode . '.apk" | tr "\n" " " | tr "//" "/"')```

In the fix, I have added one more * after $(pwd) and the command works
