### ISSUE TITLE
How to automatically import Java class package？

### ISSUE THREAD

**Issue by liuwei031015** [hsanson/vim-android#101]
I recently tried to use this plugin. Thank you very much for your work. It's great. I followed the instructions and used ALE + java-language-server and everything went well. But I don't know how to automatically import Java class package. Need to manually enter every time
"import android.app.Fragment".

**Comment by sultanahamer** [comment]
@liuwei031015 @hsanson I have installed this plugin(vim-android) along with jdtls LSP server using [lsp installer](https://github.com/williamboman/nvim-lsp-installer)

Also along with completion from https://github.com/hrsh7th/nvim-cmp

With these 3 plugins, I am able to code complete and automatically import packages.

Here is my init.vim in case you want to have a look @liuwei031015 

With this setup, I am not using ale as well.

**Comment by hsanson** [comment]
@sultanahamer I believe you missed to add the link to your init.vim file.

**Comment by sultanahamer** [comment]
@hsanson added it now. My bad.

**Comment by sultanahamer** [comment]
@hsanson I am using EclipseJDT and the classpath exported from vim-android is what making this possible. If you goto their github page, they upfront state that Android projects are not supported.

Because vim-android is giving the classpath required, it is able to work properly. Hence I am able to use auto import feature from it. I am not using ALE as of now.

One thing I want to understand is the auto complete in xml files. I don't think any xml parser etc shouldn't be able to do it on full scale.

When I mean full scale, In android projects views can define their xml attributes which these xml parsers won't have a clue about. So, was just wondering if that's already happening in this project on any level.

**Comment by hsanson** [comment]
Note that automatic import of class packages is not a goal of vim-android so I will close this issue.  Other tools like ALE/CoC can be configured to do this.

I recently learned that using eclipselsp in ALE with the g:ale_compeltion_autoimport automatically imports class packages after auto completing something. See example of this working here: https://github.com/dense-analysis/ale/discussions/4077#discussioncomment-2204572
