### ISSUE TITLE
gradle sync will execute when jumping back from taglists

### ISSUE THREAD

**Issue by cgcgbcbc** [hsanson/vim-android#52]
Isn't it supposed that it will cache results for unclosed buffer?

**Comment by hsanson** [comment]
After I implemented async processing on NeoVim the cache check was removed and I forgot to add it back again. Since with background processing works so good I did not realize the sync task was being executed every time a file was open. Thanks for letting me know.

I added a check so the sync task only executes once per build.gradle file.
