### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by pardom** [hsanson/vim-android#61]
Now that Kotlin is an officially supported language, it would be nice to have detection for Kotlin project files. Admittedly I haven't looked into implementing this as I have just installed `vim-android`. If it's simple enough, I'll PR something against this issue.

**Comment by hsanson** [comment]
I have projects that use Kotlin as main language and they work perfectly with this plugin. Note that these projects were implemented before Kotlin became officially supported.

As long as the build process is based on gradle this plugin should cover most of your needs independently of language (Java or Kotlin). In fact I wanted to rename this plugin to vim-gradle since it is actually a gradle plugin with additional android features.

If you have a sample Kotlin project that requires specific stuff to be handled by the plugin let me know. I will take time to look into them.

**Comment by piiih** [comment]
@hsanson Open a kotlin file only works if you have the kotlin-vim or another syntax plugin for kotlin, because vim doesn't understand kotlin for default. :)

I suggest to add something like that in kotlin.vim:
```vim
autocmd BufNewFile,BufRead *.kt setfiletype kotlin
autocmd BufNewFile,BufRead *.kts setfiletype kotlin
```
or

Update README with instructions to download a kotlin syntax plugin
