### ISSUE TITLE
Unknown function: android#findManifestFile

### ISSUE THREAD

**Issue by dproctor** [hsanson/vim-android#76]
I am trying to use vim-android with neovim and ALE, and according to ALEInfo, it seems like the android linter is running as expected, but I'm not getting any error messages in my editor, nor autocomplete suggestions.

:checkhealth also suggests that there might be something wrong with the way I have vim-android configured.

Thanks!

```

:ALEInfo

 Current Filetype: java                                                                                                                    
Available Linters: ['android', 'checkstyle', 'eclipselsp', 'javac', 'javalsp', 'pmd']
  Enabled Linters: ['android', 'javalsp']
....
import android.widget.NotARealClass;
                     ^
  symbol:   class NotARealClass
  location: package android.widget
1 error


:checkhealth
....
health#gradle#check
========================================================================
  - ERROR: Failed to run healthcheck for "gradle" plugin. Exception:
    function health#check[21]..health#gradle#check[2]..health#gradle#checkNvim, line 61
    Vim(if):E117: Unknown function: android#findManifestFile

```

**Comment by hsanson** [comment]
@dproctor thanks for reporting. The checkhealth issue has nothing to do with ALE and was a mistake from my part. I have submitted a fix.

I recommend you try each linter at the time since these are Java based and can be heavy on your machine. For a medium sized Android project the `android` linter can take a long time to run the first time since it lints the whole project. I have been unable to find a reliable way to lint only the current buffer.

Auto-completion is done by javalsp so you may want to check with only that linter enabled to see if it works.

On my side I use this plugin currently and both linting and auto-completion works fine. Please feel to create another issue if you still have issues.
